#!/bin/sh
set -e
export AWS_DEFAULT_REGION=us-east-1

AWS_STACK_NAMES=$(aws cloudformation list-stacks --output text --query 'StackSummaries[?StackStatus!=`DELETE_COMPLETE`].{Name:StackName}')

echo $AWS_STACK_NAMES | grep -q $AWS_STACK_NAME
