#!/bin/sh
set -e

if ./deploy/cloudformation/created ; then
  echo "stack already created. perhaps you meant to call update-stack?..."
  exit 1
fi

echo 'creating stack...'

echo sync template...
aws s3 sync ./deploy/cloudformation/templates/ s3://nickmeldrum-com-cloudformation/
echo validate template...
aws cloudformation validate-template --template-url https://s3.amazonaws.com/nickmeldrum-com-cloudformation/nickmeldrumcomblog.json
echo create stack...
export $AWS_STACK_ID=$(aws cloudformation create-stack --template-url https://s3.amazonaws.com/nickmeldrum-com-cloudformation/nickmeldrumcomblog.json --stack-name $AWS_STACK_NAME --parameters ParameterKey=BranchName,ParameterValue=$BRANCH_NAME --output text --query StackId --region us-east-1)
echo "STACK_ID $AWS_STACK_ID"
echo wait for stack completion...

if aws cloudformation wait stack-create-complete --stack-name $AWS_STACK_ID then
  echo stack created!
  aws cloudformation list-stack-resources --stack-name $AWS_STACK_ID
else
  echo getting events...
  aws cloudformation describe-stack-events --stack-name $AWS_STACK_ID --output text --query "StackEvents[*].{Status:ResourceStatus,Reason:ResourceStatusReason}"
  ./deploy/cloudformation/delete
fi
