#!/bin/sh
set -e

if ! ./deploy/cloudformation/created ; then
  echo "no stack to delete..."
  exit 1
fi

echo getting stack...
. ./deploy/cloudformation/get-stack-id

echo "deleting stack..."
aws cloudformation delete-stack --stack-name $AWS_STACK_ID
aws cloudformation wait stack-delete-complete --stack-name $AWS_STACK_ID
