#!/bin/sh
set -e

. ./deploy/cloudformation/get-stack-id

export AWS_BUCKET_ID=$(aws cloudformation list-stack-resources --stack-name $AWS_STACK_ID --output text --query "StackResourceSummaries[?ResourceType=='AWS::S3::Bucket'].[PhysicalResourceId]")
echo "BUCKET_ID $AWS_BUCKET_ID"

export AWS_CLOUDFRONT_ID=$(aws cloudformation list-stack-resources --stack-name $AWS_STACK_ID --output text --query "StackResourceSummaries[?ResourceType=='AWS::CloudFront::Distribution'].[PhysicalResourceId]")
echo "CLOUDFRONT_ID $AWS_CLOUDFRONT_ID"
