#!/bin/sh
set -e

if ! ./deploy/cloudformation/created ; then
  echo "no stack to update, did you mean to create?..."
  exit 1
fi

echo template sync...
aws s3 sync ./deploy/cloudformation/templates/ s3://nickmeldrum-com-cloudformation/
. ./deploy/cloudformation/get-stack-id
echo creating change set...
AWS_CHANGESET_ID=$(aws cloudformation create-change-set --stack-name $AWS_STACK_ID --change-set-name nmcomblog-changeset --template-url https://s3.amazonaws.com/nickmeldrum-com-cloudformation/nickmeldrumcomblog.json --parameters ParameterKey=BranchName,ParameterValue=$BRANCH_NAME --output text --query 'Id')
echo "CHANGESET_ID $AWS_CHANGESET_ID"

echo waiting for change set creation...
if aws cloudformation wait change-set-create-complete --change-set-name $AWS_CHANGESET_ID ;
then
  echo "change set created..."
  echo change set details...
  QUERY='Changes[*].[Type,ResourceChange.Action,ResourceChange.ResourceType,ResourceChange.Details[*].Target.Name,ResourceChange.Details[*].Target.Attribute]'
  aws cloudformation describe-change-set --change-set-name $AWS_CHANGESET_ID --output text --query $QUERY

  echo executing...
  aws cloudformation execute-change-set --change-set-name $AWS_CHANGESET_ID
  echo wait for stack update...
  if aws cloudformation wait stack-update-complete --stack-name $AWS_STACK_ID ;
  then
    echo stack updated!
    aws cloudformation list-stack-resources --stack-name $AWS_STACK_ID
  else
    echo stack update failed...
    echo getting events...
    aws cloudformation describe-stack-events --stack-name $AWS_STACK_ID --output text --query "StackEvents[*].{Status:ResourceStatus,Reason:ResourceStatusReason}"
  fi
else
  echo "change set creation failed!"
  if ! aws cloudformation describe-change-set --change-set-name $AWS_CHANGESET_ID --output text --query "StatusReason" | grep -q "didn't contain changes" ;
  then
    exit 1
  else
    echo "no changes necessary"
  fi
fi
