#!/bin/sh
set -e
export AWS_DEFAULT_REGION=us-east-1

export AWS_STACK_NAME=$(aws cloudformation list-stacks --output text --query 'StackSummaries[?StackStatus!=`DELETE_COMPLETE`].{Name:StackName}')
echo 'cloudformation stack name: ' $AWS_STACK_NAME
if [ $AWS_STACK_NAME = nickmeldrumcomblog-testing-infrastructure ]; then
  echo "updating stack..."
  ./cloudformation/update-stack
else
  echo "creating stack..."
  ./cloudformation/create-stack
fi
. ./cloudformation/export-s3-bucket-name
