#!/bin/sh
set -e
export AWS_DEFAULT_REGION=us-east-1

echo 'syncing s3 bucket...'
nickmeldrumcomblog_testing_infrastructure_stack_id=$(aws cloudformation describe-stacks --stack-name nickmeldrumcomblog-testing-infrastructure --output text --query 'Stacks[*].StackId' --region us-east-1)
S3_BUCKET=$(aws cloudformation list-stack-resources --stack-name $nickmeldrumcomblog_testing_infrastructure_stack_id --output text --query "StackResourceSummaries[?ResourceType=='AWS::S3::Bucket'].[PhysicalResourceId]")
echo "S3 $S3_BUCKET"
aws s3 sync _site "s3://$S3_BUCKET" --delete

echo 'getting cloudfront id...'
nickmeldrumcomblog_testing_infrastructure_stack_id=$(aws cloudformation describe-stacks --stack-name nickmeldrumcomblog-testing-infrastructure --output text --query 'Stacks[*].StackId' --region us-east-1)
AWS_CLOUDFRONT_ID_TESTING=$(aws cloudformation list-stack-resources --stack-name $nickmeldrumcomblog_testing_infrastructure_stack_id --output text --query "StackResourceSummaries[?ResourceType=='AWS::CloudFront::Distribution'].[PhysicalResourceId]" --region us-east-1)
echo "CF ID $AWS_CLOUDFRONT_ID_TESTING"

echo 'invalidating cf...'
aws configure set preview.cloudfront true
aws cloudfront create-invalidation --distribution-id "$AWS_CLOUDFRONT_ID_TESTING" --paths "/*" --output text --query "Invalidation.Status"
