#!/bin/sh
set -e
export AWS_DEFAULT_REGION=us-east-1

echo 'updating lambda code and publishing new version...'
LAMBDA_ARN=$(aws lambda update-function-code --function-name nickmeldrumcom-blog-origin-request --zip-file fileb://origin-request-function.zip --publish --output text --query 'FunctionArn' --region us-east-1)
echo "LAMBDA ARN $LAMBDA_ARN"

echo 'getting cloudfront id...'
nickmeldrumcomblog_testing_infrastructure_stack_id=$(aws cloudformation describe-stacks --stack-name nickmeldrumcomblog-testing-infrastructure --output text --query 'Stacks[*].StackId' --region us-east-1)
AWS_CLOUDFRONT_ID_TESTING=$(aws cloudformation list-stack-resources --stack-name $nickmeldrumcomblog_testing_infrastructure_stack_id --output text --query "StackResourceSummaries[?ResourceType=='AWS::CloudFront::Distribution'].[PhysicalResourceId]" --region us-east-1)
echo "CF ID $AWS_CLOUDFRONT_ID_TESTING"

echo 'updating distribution config...'
aws cloudfront get-distribution-config --id "$AWS_CLOUDFRONT_ID_TESTING" > cf-testing-config.json
node cloudformation/add-lambda-assoc.js $LAMBDA_ARN
E_TAG=$(node cloudformation/get-dist-config-etag.js)
echo "CONFIG ETAG $E_TAG"
rm cf-testing-config.json
aws cloudfront update-distribution --if-match $E_TAG --distribution-config file://cf-testing-config-new.json --id "$AWS_CLOUDFRONT_ID_TESTING" --output text --query 'Distribution.Status'
rm cf-testing-config-new.json

# echo 'waiting for distribution to be deployed...'
# aws cloudfront wait distribution-deployed --id "$AWS_CLOUDFRONT_ID_TESTING"
