#!/bin/sh
set -e
export AWS_DEFAULT_REGION=us-east-1

nickmeldrumcomblog_testing_infrastructure_stack_id=$(aws cloudformation describe-stacks --stack-name nickmeldrumcomblog-testing-infrastructure --output text --query 'Stacks[*].StackId' --region us-east-1)
export AWS_CLOUDFRONT_ID_TESTING=$(aws cloudformation list-stack-resources --stack-name $nickmeldrumcomblog_testing_infrastructure_stack_id --output text --query "StackResourceSummaries[?ResourceType=='AWS::CloudFront::Distribution'].[PhysicalResourceId]")
echo 'set testing cloudfront id' $AWS_CLOUDFRONT_ID_TESTING
