#!/bin/sh
set -e

echo 'updating distribution config...'
aws cloudfront get-distribution-config --id "$AWS_CLOUDFRONT_ID" > cf-testing-config.json
node ./deploy/cloudfront/add-lambda-assoc.js $AWS_ORIGIN_REQUEST_LAMBDA_ID
E_TAG=$(node ./deploy/cloudfront/get-dist-config-etag.js)
echo "CONFIG_ETAG $E_TAG"
rm cf-testing-config.json
aws cloudfront update-distribution --if-match $E_TAG --distribution-config file://cf-testing-config-new.json --id "$AWS_CLOUDFRONT_ID" --output text --query 'Distribution.Status'
rm cf-testing-config-new.json

# echo 'waiting for distribution to be deployed...'
# aws cloudfront wait distribution-deployed --id "$AWS_CLOUDFRONT_ID"
