#!/bin/sh
set -e
export AWS_DEFAULT_REGION=us-east-1
echo "DEFAULT_REGION $AWS_DEFAULT_REGION"
if [ $BRANCH_NAME = 'master' ]; then
export AWS_STACK_NAME=nickmeldrumcomblog-production
export AWS_LAMBDA_NAME=nickmeldrumcomblog-originrequest-production
else
export AWS_STACK_NAME=nickmeldrumcomblog-testing
export AWS_LAMBDA_NAME=nickmeldrumcomblog-originrequest-testing
fi
echo "STACK_NAME $AWS_STACK_NAME"
echo "LAMBDA_NAME $AWS_LAMBDA_NAME"

# other vars exported in scripts:
# AWS_STACK_ID
# AWS_BUCKET_ID
# AWS_CLOUDFRONT_ID
