#!/bin/sh
set -e
export AWS_DEFAULT_REGION=us-east-1

. ./deploy/init-vars

. ./deploy/cloudformation/create-or-update
. ./deploy/cloudformation/get-resource-ids

. ./deploy/s3/sync
. ./deploy/cloudfront/invalidate-cache

. ./deploy/lambda/update
. ./deploy/cloudfront/update-distribution
