#!/bin/sh
export PATH=./script:./cloudformation:"$PATH"
echo "### jekyll/lambda commands:"
find ./script -maxdepth 2 -perm -111 -type f | sed -n '/init/ !p' | sed -e 's/\.\/script\///'
echo
echo "### cloudformation commands:"
find ./cloudformation -maxdepth 2 -perm -111 -type f | sed -n '/init/ !p' | sed -e 's/\.\/cloudformation\///'
