#!/bin/sh
set -e
export AWS_DEFAULT_REGION=us-east-1

aws s3api create-bucket --bucket nickmeldrum-com-cloudformation --region us-east-1 --acl private
aws s3api put-bucket-versioning --bucket nickmeldrum-com-cloudformation --versioning-configuration Status=Enabled
